server:
  port: 8080 # Puerto del Gateway

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000
  cloud:
    gateway:
      routes:
        - id: ms-Alejandro
          uri: lb://ms-Alejandro # lb = load balanced (balanceo de carga)
          predicates:
            - Path=/api/entity-a/** # Si la URL empieza con /api/entity-a/
          filters:
            - StripPrefix=0 # No elimina ninguna parte del path
        
        - id: ms-b-Alejandro
          uri: lb://ms-b-Alejandro
          predicates:
            - Path=/api/entity-b/**
          filters:
            - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: http://server:8761/eureka/